### PR TITLE
Autocomplete

### PR DESCRIPTION
**Pull request by andrewtobin**
Some notes:

There didn't seem to be a complete way to put data in, so I used this to test it (from the search.js route).
      var tests = ["test", "test2", "test3", "typeahead", "typeahead2"];
      if (req.accepts('json')) { return res.json(tests); }
- I put the json return "if" before the 0 results "if" in search.js because if there was 0 results it was returning a html page.
- I moved the jquery up above the body in the layout because you couldn't use jquery before it was defined - if you want to point out how it should go, then I'm happy to adjust
- I wanted to use the built in bootstrap version of typeahead but it doesn't use ajax, so I used an adjusted version sourced https://gist.github.com/1891669 - other thoughts were just to use the jquery ui but after some playing I got it to work.

### CODE REVIEW

**Comment by csainty** [comment]
Generally looks pretty good.

Not sure I like the javascript function as text, screams sql injection to me. Ideally we probably want a dedicated text search plugin, I am looking at ElasticSearch atm. We could also look at the RegEx query filter instead of the function, has similar problem though, you are going to have to dump the search text in the regex. Honeslty haven't researched whther the function method is a good vector for SQL injection, it just feels like it would be.

Other comment I would make is on the script tags, they have been shifted back into the header. Jade has a really funky feature where you can define your sections (like asp.net) but then you can prepend/append to the them from your child pages.

https://github.com/visionmedia/jade#a12

It would be great if we can keep our scripts at the bottom and use this technique to add page specific scripts after the defaults load.

**Comment by andrewtobin** [comment]
Thanks, that's pretty much exactly the feedback I was hoping for - given I have very little knowledge on what to do.

Can you have SQL Injection without SQL? ;)  I'll see what other options there are and look into the link you gave.

**Comment by andrewtobin** [comment]
That does the templating, and now looking for a search engine

**Comment by csainty** [comment]
Merged manually.

**Pull request merged**
