### PR TITLE
Ask Question - receive form data and save record to data store

### PR DESCRIPTION
**Pull request by mjhilton**
Implemented basic Wat creation. Temporarily using test data for user until auth is done. Redirects to home page after creation, there's another card for the "pending" page.

### CODE REVIEW

**Comment by csainty** [comment]
What do people think about the GET /ask and POST /create?

If we are trying to make an API out of the site, then we should probably be POST/PUT to /wat.
We can then use the json/html check to determine whether we redirect or return a result code.

/ask is really a HTML only route, so it could stay with a nice friendly value.

**Comment by mjhilton** [comment]
Yep I'm in favour. Shall I close the pull request and re-work it as above?

**Comment by csainty** [comment]
Typically you should be sending your PR from a branch, not from master, then when you push new changes to the branch it also updates the PR. Not sure how that works when you create the PR from master, probably the same though.

**Comment by mjhilton** [comment]
Okay... git/github n00b here ;) will create a branch for it and re-do to put to /wat :)

**Comment by csainty** [comment]
Pulled and merged. Don't get too hung up on the whole post/put I was just thinking out loud for later on.
I've rearranged the routes a little to handle multiple, related, routes in a single file. So take a look at the latest to see how I merged ask.js and create.js

**Comment by mjhilton** [comment]
Thanks Chris :)

**Pull request merged**
